-- =====================================================
-- MALDIVES AI RETAIL CONCIERGE - Seed data
-- Run after schema.sql in the Supabase SQL editor.
-- Safe to run multiple times.
-- =====================================================

begin;

insert into brands (name, slug, source_country, is_verified)
values
  ('boAt', 'boat', 'India', true),
  ('Mamaearth', 'mamaearth', 'India', true),
  ('Mivi', 'mivi', 'India', false),
  ('Wakefit', 'wakefit', 'India', false),
  ('Noise', 'noise', 'India', false),
  ('Nykaa', 'nykaa', 'India', false),
  ('Plum', 'plum', 'India', false),
  ('Wildcraft', 'wildcraft', 'India', false),
  ('Studio Linen', 'studio-linen', 'India', false),
  ('Nida Closet', 'nida-closet', 'India', false),
  ('Stride', 'stride', 'India', false),
  ('Atoll', 'atoll', 'Maldives', false),
  ('Volt', 'volt', 'India', false),
  ('Vox', 'vox', 'India', false),
  ('Lyra', 'lyra', 'India', false),
  ('Kickstart', 'kickstart', 'India', false)
on conflict (slug) do update set
  name = excluded.name,
  source_country = excluded.source_country,
  is_verified = excluded.is_verified;

insert into categories (name, slug, icon, color_gradient, image_url, sort_order, blurb, product_count)
values
  ('Garments', 'garments', 'Shirt', 'from-rose-400 to-rose-600', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?crop=entropy&cs=srgb&fm=jpg&q=85&w=940', 10, 'Fashion, modestwear and branded apparel', 28),
  ('Cosmetics', 'cosmetics', 'Sparkles', 'from-pink-400 to-fuchsia-600', 'https://images.pexels.com/photos/9620358/pexels-photo-9620358.jpeg?auto=compress&cs=tinysrgb&w=940', 20, 'Skincare, beauty, haircare and wellness', 42),
  ('Electronics', 'electronics', 'Smartphone', 'from-cyan-500 to-blue-700', 'https://images.unsplash.com/photo-1636115305669-9096bffe87fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=940', 30, 'Earbuds, wearables and accessories', 56),
  ('Gaming', 'gaming', 'Gamepad2', 'from-violet-500 to-indigo-700', 'https://images.pexels.com/photos/7858742/pexels-photo-7858742.jpeg?auto=compress&cs=tinysrgb&w=940', 40, 'Headsets, controllers and keyboards', 31),
  ('Shoes', 'shoes', 'Footprints', 'from-amber-500 to-orange-700', 'https://images.pexels.com/photos/4061395/pexels-photo-4061395.jpeg?auto=compress&cs=tinysrgb&w=940', 50, 'Sneakers, sports and lifestyle footwear', 24),
  ('Musical', 'musical', 'Music', 'from-emerald-500 to-teal-700', 'https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?crop=entropy&cs=srgb&fm=jpg&q=85&w=940', 60, 'Audio, instruments and microphones', 18),
  ('Sports', 'sports', 'Dumbbell', 'from-lime-500 to-emerald-700', 'https://images.unsplash.com/photo-1602211844066-d3bb556e983b?crop=entropy&cs=srgb&fm=jpg&q=85&w=940', 70, 'Gym, football, cricket and fitness', 22)
on conflict (slug) do update set
  name = excluded.name,
  icon = excluded.icon,
  color_gradient = excluded.color_gradient,
  image_url = excluded.image_url,
  sort_order = excluded.sort_order,
  blurb = excluded.blurb,
  product_count = excluded.product_count;

create unique index if not exists idx_delivery_zones_island_name on delivery_zones(island_name);

insert into delivery_zones (island_name, atoll, delivery_fee_mvr, extra_min_days, extra_max_days, courier_partner, is_active)
values
  ('Male', 'Kaafu', 50, 0, 1, 'Local same-day', true),
  ('Hulhumale', 'Kaafu', 60, 0, 2, 'Local same-day', true),
  ('Villimale', 'Kaafu', 70, 1, 2, 'Local', true),
  ('Addu (Hithadhoo)', 'Seenu', 150, 2, 5, 'FlyMe Cargo', true),
  ('Gan', 'Seenu', 150, 2, 5, 'FlyMe Cargo', true),
  ('Fuvahmulah', 'Gnaviyani', 140, 2, 5, 'FlyMe Cargo', true),
  ('Kulhudhuffushi', 'Haa Dhaalu', 130, 2, 5, 'Maldivian Air Cargo', true),
  ('Thinadhoo', 'Gaafu Dhaalu', 130, 2, 5, 'Maldivian Air Cargo', true),
  ('Hoarafushi', 'Haa Alifu', 140, 3, 6, 'Speedboat + Air', true),
  ('Eydhafushi', 'Baa', 110, 2, 4, 'Speedboat', true),
  ('Naifaru', 'Lhaviyani', 110, 2, 4, 'Speedboat', true),
  ('Mahibadhoo', 'Alif Dhaal', 110, 2, 4, 'Speedboat', true)
on conflict (island_name) do update set
  atoll = excluded.atoll,
  delivery_fee_mvr = excluded.delivery_fee_mvr,
  extra_min_days = excluded.extra_min_days,
  extra_max_days = excluded.extra_max_days,
  courier_partner = excluded.courier_partner,
  is_active = excluded.is_active;

with seed_products (
  sku, slug, title, brand_name, category_slug, subcategory,
  short_description, description, source_country, source_currency, source_price,
  price_mvr, compare_at_price_mvr, product_type, stock_status, preorder,
  estimated_delivery_min_days, estimated_delivery_max_days, main_image_url,
  gallery_images, size_options, color_options, specifications, warranty,
  is_featured, badges
) as (
  values
    ('BOAT-AIR-141-BLK', 'boat-airdopes-141', 'boAt Airdopes 141 Wireless Earbuds', 'boAt', 'electronics', 'Earbuds',
      '42-hour playtime wireless earbuds with deep bass',
      'Crystal-clear sound, fast top-ups, and IPX4 sweat resistance. Perfect for calls, workouts, and island travel.',
      'India', 'INR', 1299, 399, 599, 'preorder', 'preorder', true, 7, 14,
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80',
      '["https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80"]',
      '[]', '["Black","White","Active Blue"]', '{"battery":"Up to 42 hours","connectivity":"Bluetooth 5.1","waterproof":"IPX4"}',
      '1-year supplier warranty', true, '["India Pre-order","Best Value"]'),
    ('NOISE-SMW-COLORFIT', 'noise-colorfit-pro-5', 'Noise ColorFit Pro 5 Smartwatch', 'Noise', 'electronics', 'Smartwatch',
      '1.85 inch AMOLED with Bluetooth calling and SpO2',
      'Stay on top of fitness, calls and notifications. Premium aluminum frame and 7-day battery life.',
      'India', 'INR', 4999, 1499, 2199, 'preorder', 'preorder', true, 7, 14,
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
      '["https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80"]',
      '[]', '["Jet Black","Rose Gold","Silver"]', '{"display":"1.85 inch AMOLED","battery":"7 days","waterproof":"IP68"}',
      null, true, '["India Pre-order","Original Brand"]'),
    ('MIVI-DUO-PRO', 'mivi-duo-pro-speaker', 'Mivi Duo Pro Portable Speaker', 'Mivi', 'electronics', 'Speaker',
      'Stereo Bluetooth speaker with 24-hour playtime',
      'Designed in India, tested for the tropics. IPX6 waterproof and beach-ready.',
      'India', 'INR', 2299, 699, 999, 'preorder', 'preorder', true, 8, 15,
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Onyx","Sand"]', '{"battery":"24h","waterproof":"IPX6"}',
      null, false, '["India Pre-order"]'),
    ('BOAT-STONE-352', 'boat-stone-352-speaker', 'boAt Stone 352 Bluetooth Speaker', 'boAt', 'electronics', 'Speaker',
      '10W IPX7 portable speaker',
      'Built for the beach and the boat. 12-hour playtime with built-in mic.',
      'India', 'INR', null, 549, 799, 'ready_stock', 'in_stock', false, 1, 3,
      'https://images.unsplash.com/photo-1610465299996-30f240ac2b1c?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Black","Red"]', '{"battery":"12h","waterproof":"IPX7"}',
      null, true, '["Ready in Maldives","Fast Sourcing"]'),
    ('MAMA-VITC-50ML', 'mamaearth-vitamin-c-face-wash', 'Mamaearth Vitamin C Face Wash', 'Mamaearth', 'cosmetics', 'Skincare',
      'Brightening face wash with Vitamin C and Turmeric',
      'Gently cleanses while brightening dull skin. Made safe certified and paraben-free.',
      'India', 'INR', 249, 129, 199, 'preorder', 'preorder', true, 7, 12,
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80',
      '[]', '["100ml","150ml"]', '[]', '{"skin_type":"All","paraben_free":"Yes"}',
      'Returns only for damaged items', true, '["India Pre-order","Original Brand"]'),
    ('MAMA-SUN-SPF50', 'mamaearth-sunscreen-spf50', 'Mamaearth Ultra Light SPF 50 Sunscreen', 'Mamaearth', 'cosmetics', 'Skincare',
      'Broad-spectrum SPF 50 with Aloe Vera',
      'Lightweight, non-greasy sunscreen for tropical sun.',
      'India', 'INR', null, 159, 249, 'preorder', 'preorder', true, 7, 12,
      'https://images.unsplash.com/photo-1556228852-80b6e5eeff06?auto=format&fit=crop&w=900&q=80',
      '[]', '["50ml","80ml"]', '[]', '{}',
      null, true, '["India Pre-order","Best Value"]'),
    ('PLUM-NIA-SER', 'plum-niacinamide-serum', 'Plum 5% Niacinamide Serum', 'Plum', 'cosmetics', 'Skincare',
      'Pore minimizing serum with rice water',
      'Visibly reduces pores and oil. Vegan and cruelty-free.',
      'India', 'INR', null, 219, 299, 'preorder', 'preorder', true, 8, 14,
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80',
      '[]', '["15ml","30ml"]', '[]', '{}',
      null, false, '["India Pre-order"]'),
    ('MAMA-HOIL-200', 'mamaearth-onion-hair-oil', 'Mamaearth Onion Hair Oil 250ml', 'Mamaearth', 'cosmetics', 'Haircare',
      'Hair fall control oil with onion and redensyl',
      'Strengthens hair from the roots. Family-size 250ml bottle.',
      'India', 'INR', null, 189, 259, 'preorder', 'preorder', true, 7, 12,
      'https://images.unsplash.com/photo-1631730486572-226d1f595b68?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '[]', '{}',
      null, false, '["India Pre-order","Original Brand"]'),
    ('GAR-COT-TSHIRT-01', 'premium-cotton-tee', 'Premium Cotton Crew Tee', 'Studio Linen', 'garments', 'Casual',
      'Heavyweight 240gsm cotton, garment-dyed',
      'Soft hand-feel and drop-shoulder fit. Sourced from Tirupur, India.',
      'India', 'INR', null, 249, 349, 'preorder', 'preorder', true, 9, 16,
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
      '[]', '["S","M","L","XL","XXL"]', '["White","Sand","Charcoal","Ocean"]', '{}',
      null, false, '["India Pre-order"]'),
    ('GAR-MODEST-ABAYA', 'modest-pearl-abaya', 'Pearl Embellished Modest Abaya', 'Nida Closet', 'garments', 'Modestwear',
      'Open-style abaya with pearl trim',
      'Elegant evening abaya tailored for Maldivian women. Premium Nida crepe.',
      'India', 'INR', null, 899, 1299, 'preorder', 'preorder', true, 10, 18,
      'https://images.unsplash.com/photo-1604762524889-3e2fcc145683?auto=format&fit=crop&w=900&q=80',
      '[]', '["S","M","L","XL"]', '["Pearl Black","Midnight Navy","Sand"]', '{}',
      null, true, '["India Pre-order","Original Brand"]'),
    ('GAR-LINEN-SHIRT', 'island-linen-shirt', 'Island Linen Resort Shirt', 'Studio Linen', 'garments', 'Casual',
      'Pure linen short-sleeve resort shirt',
      'Built for island weather. Breathable and lightweight.',
      'India', 'INR', null, 459, 649, 'preorder', 'preorder', true, 9, 16,
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80',
      '[]', '["S","M","L","XL"]', '["White","Ocean","Olive"]', '{}',
      null, false, '["India Pre-order"]'),
    ('SHOE-RUN-FLEX-01', 'flex-run-sneakers', 'Flex Run Performance Sneakers', 'Stride', 'shoes', 'Running',
      'Lightweight running shoes with EVA foam',
      'Engineered mesh upper, EVA midsole and rubber outsole. Daily trainer.',
      'India', 'INR', null, 799, 1299, 'preorder', 'preorder', true, 9, 16,
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
      '[]', '["7","8","9","10","11"]', '["Black/White","Navy/Coral","Grey/Mint"]', '{}',
      null, true, '["India Pre-order","Best Value"]'),
    ('SHOE-LIFE-CLASSIC', 'classic-lifestyle-sneaker', 'Heritage Classic Sneakers', 'Stride', 'shoes', 'Lifestyle',
      'Vintage tennis silhouette in white leather',
      'Timeless white sneaker. Goes with everything.',
      'India', 'INR', null, 749, 1099, 'preorder', 'preorder', true, 9, 16,
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80',
      '[]', '["7","8","9","10","11"]', '["White","Off White"]', '{}',
      null, false, '["India Pre-order"]'),
    ('SHOE-BEACH-FLIP', 'tropic-beach-flipflop', 'Tropic Beach Flip Flops', 'Atoll', 'shoes', 'Sandals',
      'Quick-dry beach sandals',
      'Soft EVA footbed and grip outsole. Perfect for resort staff.',
      'Maldives', 'MVR', null, 149, 249, 'ready_stock', 'in_stock', false, 1, 3,
      'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80',
      '[]', '["7","8","9","10","11"]', '["Black","Coral","Teal"]', '{}',
      null, false, '["Ready in Maldives"]'),
    ('GAME-HSET-RGB', 'phantom-rgb-headset', 'Phantom RGB Gaming Headset', 'Volt', 'gaming', 'Headset',
      '7.1 surround with RGB lighting',
      'Plush memory foam ear-cups and noise-cancelling mic.',
      'India', 'INR', null, 1199, 1899, 'preorder', 'preorder', true, 8, 15,
      'https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["RGB Black"]', '{"audio":"7.1 Surround","mic":"Detachable"}',
      null, true, '["India Pre-order","Original Brand"]'),
    ('GAME-CTRL-WL', 'ace-wireless-controller', 'Ace Wireless Controller', 'Volt', 'gaming', 'Controller',
      'Bluetooth controller for PC and mobile',
      'Hall-effect joysticks and low-latency wireless.',
      'India', 'INR', null, 999, 1499, 'preorder', 'preorder', true, 8, 15,
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Black","White"]', '{}',
      null, false, '["India Pre-order"]'),
    ('GAME-KEY-MECH', 'viper-tkl-mechanical', 'Viper TKL Mechanical Keyboard', 'Volt', 'gaming', 'Keyboard',
      '75% layout with hot-swappable switches',
      'PBT keycaps and RGB per-key lighting in a compact desk-friendly form factor.',
      'India', 'INR', null, 1599, 2299, 'preorder', 'preorder', true, 9, 16,
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Black"]', '{}',
      null, false, '["India Pre-order"]'),
    ('MUS-MIC-USB', 'studio-usb-mic', 'StudioCast USB Condenser Mic', 'Vox', 'musical', 'Microphone',
      'Plug-and-play cardioid USB mic',
      'Perfect for podcasts, streaming, and bedroom producers.',
      'India', 'INR', null, 899, 1399, 'preorder', 'preorder', true, 8, 15,
      'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Black"]', '{}',
      null, false, '["India Pre-order"]'),
    ('MUS-GUITAR-AC', 'acoustic-cutaway', 'Acoustic Cutaway Guitar', 'Lyra', 'musical', 'Guitar',
      'Spruce top dreadnought with cutaway',
      'Bright, balanced tone. Great for beginners and gigging.',
      'India', 'INR', null, 2999, 3899, 'preorder', 'preorder', true, 12, 20,
      'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Natural","Sunburst"]', '{}',
      null, true, '["India Pre-order","Custom Sourcing"]'),
    ('MUS-SPK-PORTABLE', 'lyra-portable-amp', 'Lyra Portable Busker Amp', 'Lyra', 'musical', 'Amp',
      'Battery-powered 20W amp',
      'Take your sound anywhere. 8-hour battery.',
      'India', 'INR', null, 1799, 2299, 'preorder', 'preorder', true, 10, 17,
      'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '[]', '{}',
      null, false, '["India Pre-order"]'),
    ('SPT-FOOTBALL-FIFA', 'match-football-size5', 'Match Football Size 5', 'Kickstart', 'sports', 'Football',
      'FIFA quality size 5 match ball',
      'Hand-stitched panels with a durable PU exterior.',
      'India', 'INR', null, 299, 449, 'preorder', 'preorder', true, 8, 14,
      'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0a72?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '[]', '{}',
      null, false, '["India Pre-order"]'),
    ('SPT-GLOVES-LIFT', 'lift-pro-gym-gloves', 'Lift Pro Gym Gloves', 'Kickstart', 'sports', 'Gym',
      'Leather palm gym gloves',
      'Wrist wraps included. For deadlifts, pulls, and curls.',
      'India', 'INR', null, 199, 299, 'preorder', 'preorder', true, 7, 14,
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80',
      '[]', '["S","M","L","XL"]', '[]', '{}',
      null, false, '["India Pre-order"]'),
    ('SPT-YOGAMAT-6MM', 'ocean-yoga-mat-6mm', 'Ocean Yoga Mat 6mm', 'Atoll', 'sports', 'Yoga',
      'Non-slip TPE yoga mat, 6mm thick',
      'Eco-friendly TPE and anti-tear build for hot yoga and pilates.',
      'India', 'INR', null, 349, 499, 'preorder', 'preorder', true, 8, 15,
      'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Ocean","Coral","Sand"]', '{}',
      null, true, '["India Pre-order","Best Value"]'),
    ('SPT-CRICKET-BAT', 'willow-cricket-bat', 'Willow Pro Cricket Bat', 'Kickstart', 'sports', 'Cricket',
      'Kashmir willow bat, short-handle',
      'Light pickup and big edges. Tournament ready.',
      'India', 'INR', null, 1199, 1599, 'preorder', 'preorder', true, 10, 18,
      'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '[]', '{}',
      null, false, '["India Pre-order"]'),
    ('ELEC-CHRG-65W', 'rapid-65w-charger', 'Rapid 65W GaN Charger', 'boAt', 'electronics', 'Charger',
      'Compact GaN PD charger with 3 ports',
      'Charge laptop, phone and earbuds together.',
      'India', 'INR', null, 599, 899, 'preorder', 'preorder', true, 7, 14,
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '[]', '{}',
      null, false, '["India Pre-order"]'),
    ('COSM-LIPSTK-MATTE', 'matte-lipstick-velvet', 'Velvet Matte Lipstick', 'Nykaa', 'cosmetics', 'Makeup',
      'Long-stay matte finish lipstick',
      '8-hour wear with a cruelty-free formula.',
      'India', 'INR', null, 99, 169, 'preorder', 'preorder', true, 7, 12,
      'https://images.unsplash.com/photo-1631214524020-3c8167274cf4?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Rose","Coral","Brick","Berry"]', '{}',
      null, false, '["India Pre-order"]'),
    ('GAR-KID-TEE', 'kids-cotton-tee', $$Kids' Soft Cotton Tee$$, 'Studio Linen', 'garments', 'Kidswear',
      'Breathable cotton tee for kids',
      'Designed for tropical comfort.',
      'India', 'INR', null, 149, 219, 'preorder', 'preorder', true, 9, 15,
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80',
      '[]', '["2T","4T","6","8","10"]', '["Sky","Coral","Cream"]', '{}',
      null, false, '["India Pre-order"]'),
    ('GAME-MOUSE-WL', 'viper-light-mouse', 'Viper Light Wireless Mouse', 'Volt', 'gaming', 'Mouse',
      'Ultralight wireless gaming mouse',
      '59g chassis with a 26K DPI sensor.',
      'India', 'INR', null, 1399, 1899, 'preorder', 'preorder', true, 9, 16,
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '[]', '{}',
      null, false, '["India Pre-order"]'),
    ('MUS-EARPHONE-WIRED', 'tunepods-wired-earphones', 'TunePods Wired Earphones', 'boAt', 'musical', 'Earphones',
      'Wired in-ear earphones with mic',
      'Crisp bass and in-line mic. Affordable backup pair.',
      'India', 'INR', null, 89, 149, 'ready_stock', 'in_stock', false, 1, 3,
      'https://images.unsplash.com/photo-1612444530582-fc66183b16f6?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '[]', '{}',
      null, false, '["Ready in Maldives"]'),
    ('SPT-DUMB-PAIR', 'neoprene-dumbbells', 'Neoprene Dumbbells (Pair)', 'Kickstart', 'sports', 'Gym',
      'Pair of 5kg neoprene dumbbells',
      $$Easy-grip, hex shape. Won't roll.$$,
      'India', 'INR', null, 549, 799, 'preorder', 'preorder', true, 12, 20,
      'https://images.unsplash.com/photo-1517344884509-a0c97ec11bcc?auto=format&fit=crop&w=900&q=80',
      '[]', '[]', '["Coral","Teal"]', '{}',
      null, false, '["India Pre-order"]')
)
insert into products (
  sku, slug, title, brand_id, category_id, subcategory, short_description, description,
  source_country, source_currency, source_price, price_mvr, compare_at_price_mvr,
  product_type, stock_status, preorder, estimated_delivery_min_days, estimated_delivery_max_days,
  main_image_url, gallery_images, size_options, color_options, specifications, warranty,
  is_featured, badges, status, is_active, updated_at
)
select
  p.sku,
  p.slug,
  p.title,
  b.id,
  c.id,
  p.subcategory,
  p.short_description,
  p.description,
  p.source_country,
  p.source_currency,
  p.source_price,
  p.price_mvr,
  p.compare_at_price_mvr,
  p.product_type,
  p.stock_status,
  p.preorder,
  p.estimated_delivery_min_days,
  p.estimated_delivery_max_days,
  p.main_image_url,
  p.gallery_images::jsonb,
  p.size_options::jsonb,
  p.color_options::jsonb,
  p.specifications::jsonb,
  p.warranty,
  p.is_featured,
  p.badges::jsonb,
  'published',
  true,
  now()
from seed_products p
join brands b on b.name = p.brand_name
join categories c on c.slug = p.category_slug
on conflict (slug) do update set
  sku = excluded.sku,
  title = excluded.title,
  brand_id = excluded.brand_id,
  category_id = excluded.category_id,
  subcategory = excluded.subcategory,
  short_description = excluded.short_description,
  description = excluded.description,
  source_country = excluded.source_country,
  source_currency = excluded.source_currency,
  source_price = excluded.source_price,
  price_mvr = excluded.price_mvr,
  compare_at_price_mvr = excluded.compare_at_price_mvr,
  product_type = excluded.product_type,
  stock_status = excluded.stock_status,
  preorder = excluded.preorder,
  estimated_delivery_min_days = excluded.estimated_delivery_min_days,
  estimated_delivery_max_days = excluded.estimated_delivery_max_days,
  main_image_url = excluded.main_image_url,
  gallery_images = excluded.gallery_images,
  size_options = excluded.size_options,
  color_options = excluded.color_options,
  specifications = excluded.specifications,
  warranty = excluded.warranty,
  is_featured = excluded.is_featured,
  badges = excluded.badges,
  status = excluded.status,
  is_active = excluded.is_active,
  updated_at = now();

with seed_reviews (customer_name, island, rating, comment, is_verified, is_published) as (
  values
    ('Aishath M.', 'Male', 5, 'Got my boAt earbuds in 10 days. Original, sealed box. WhatsApp updates were excellent.', true, true),
    ('Hussain A.', 'Addu (Hithadhoo)', 5, $$Delivered to Hithadhoo without any drama. Best Maldives store I've used.$$, true, true),
    ('Fathmath I.', 'Fuvahmulah', 5, 'Mamaearth products are hard to find here. Glad this exists!', true, true),
    ('Mariyam Z.', 'Hulhumale', 4, 'Pre-order took 12 days but the price was unbeatable.', true, true)
)
insert into reviews (customer_name, island, rating, comment, is_verified, is_published)
select sr.customer_name, sr.island, sr.rating, sr.comment, sr.is_verified, sr.is_published
from seed_reviews sr
where not exists (
  select 1
  from reviews r
  where r.customer_name = sr.customer_name
    and r.comment = sr.comment
);

commit;
