// Maldives island delivery zones + small atoll list
export const ISLANDS = [
  { island: "Male", atoll: "Kaafu", fee: 50, min: 0, max: 1, courier: "Local same-day" },
  { island: "Hulhumale", atoll: "Kaafu", fee: 60, min: 0, max: 2, courier: "Local same-day" },
  { island: "Villimale", atoll: "Kaafu", fee: 70, min: 1, max: 2, courier: "Local" },
  { island: "Addu (Hithadhoo)", atoll: "Seenu", fee: 150, min: 2, max: 5, courier: "FlyMe Cargo" },
  { island: "Gan", atoll: "Seenu", fee: 150, min: 2, max: 5, courier: "FlyMe Cargo" },
  { island: "Fuvahmulah", atoll: "Gnaviyani", fee: 140, min: 2, max: 5, courier: "FlyMe Cargo" },
  { island: "Kulhudhuffushi", atoll: "Haa Dhaalu", fee: 130, min: 2, max: 5, courier: "Maldivian Air Cargo" },
  { island: "Thinadhoo", atoll: "Gaafu Dhaalu", fee: 130, min: 2, max: 5, courier: "Maldivian Air Cargo" },
  { island: "Hoarafushi", atoll: "Haa Alifu", fee: 140, min: 3, max: 6, courier: "Speedboat + Air" },
  { island: "Eydhafushi", atoll: "Baa", fee: 110, min: 2, max: 4, courier: "Speedboat" },
  { island: "Naifaru", atoll: "Lhaviyani", fee: 110, min: 2, max: 4, courier: "Speedboat" },
  { island: "Mahibadhoo", atoll: "Alif Dhaal", fee: 110, min: 2, max: 4, courier: "Speedboat" },
];

export const CATEGORIES = [
  { slug: "garments", name: "Garments", icon: "Shirt", gradient: "from-rose-400 to-rose-600", img: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?crop=entropy&cs=srgb&fm=jpg&q=85&w=940", count: 28, blurb: "Fashion, modestwear & branded apparel" },
  { slug: "cosmetics", name: "Cosmetics", icon: "Sparkles", gradient: "from-pink-400 to-fuchsia-600", img: "https://images.pexels.com/photos/9620358/pexels-photo-9620358.jpeg?auto=compress&cs=tinysrgb&w=940", count: 42, blurb: "Skincare, beauty, haircare & wellness" },
  { slug: "electronics", name: "Electronics", icon: "Smartphone", gradient: "from-cyan-500 to-blue-700", img: "https://images.unsplash.com/photo-1636115305669-9096bffe87fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=940", count: 56, blurb: "Earbuds, wearables, accessories" },
  { slug: "gaming", name: "Gaming", icon: "Gamepad2", gradient: "from-violet-500 to-indigo-700", img: "https://images.pexels.com/photos/7858742/pexels-photo-7858742.jpeg?auto=compress&cs=tinysrgb&w=940", count: 31, blurb: "Headsets, controllers, keyboards" },
  { slug: "shoes", name: "Shoes", icon: "Footprints", gradient: "from-amber-500 to-orange-700", img: "https://images.pexels.com/photos/4061395/pexels-photo-4061395.jpeg?auto=compress&cs=tinysrgb&w=940", count: 24, blurb: "Sneakers, sports & lifestyle footwear" },
  { slug: "musical", name: "Musical", icon: "Music", gradient: "from-emerald-500 to-teal-700", img: "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?crop=entropy&cs=srgb&fm=jpg&q=85&w=940", count: 18, blurb: "Audio, instruments & microphones" },
  { slug: "sports", name: "Sports", icon: "Dumbbell", gradient: "from-lime-500 to-emerald-700", img: "https://images.unsplash.com/photo-1602211844066-d3bb556e983b?crop=entropy&cs=srgb&fm=jpg&q=85&w=940", count: 22, blurb: "Gym, football, cricket, fitness" },
];

export const BRANDS = [
  { name: "boAt", slug: "boat", verified: true, country: "India" },
  { name: "Mamaearth", slug: "mamaearth", verified: true, country: "India" },
  { name: "Mivi", slug: "mivi", verified: false, country: "India" },
  { name: "Wakefit", slug: "wakefit", verified: false, country: "India" },
  { name: "Noise", slug: "noise", verified: false, country: "India" },
  { name: "Nykaa", slug: "nykaa", verified: false, country: "India" },
  { name: "Plum", slug: "plum", verified: false, country: "India" },
  { name: "Wildcraft", slug: "wildcraft", verified: false, country: "India" },
];

const img = (q, sig) => `https://images.unsplash.com/${q}?auto=format&fit=crop&w=900&q=80&ixid=${sig}`;

// 30 demo products with realistic data
export const PRODUCTS = [
  // ---- electronics
  { id: "p1", sku: "BOAT-AIR-141-BLK", slug: "boat-airdopes-141", title: "boAt Airdopes 141 Wireless Earbuds", brand: "boAt", category: "electronics", subcategory: "Earbuds", short_description: "42-hour playtime wireless earbuds with deep bass", description: "Crystal-clear sound, ASAP charge for fast top-ups, and IPX4 sweat resistance. Perfect for calls, workouts, and island travel.", price_mvr: 399, compare_at_price_mvr: 599, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 7, estimated_delivery_max_days: 14, source_country: "India", source_currency: "INR", source_price: 1299, main_image_url: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80", gallery_images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80", "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80"], color_options: ["Black", "White", "Active Blue"], specifications: { battery: "Up to 42 hours", connectivity: "Bluetooth 5.1", waterproof: "IPX4" }, warranty: "1-year supplier warranty", is_featured: true, badges: ["India Pre-order", "Best Value"] },
  { id: "p2", sku: "NOISE-SMW-COLORFIT", slug: "noise-colorfit-pro-5", title: "Noise ColorFit Pro 5 Smartwatch", brand: "Noise", category: "electronics", subcategory: "Smartwatch", short_description: "1.85\" AMOLED with Bluetooth calling & SpO2", description: "Stay on top of fitness, calls and notifications. Premium aluminum frame and 7-day battery life.", price_mvr: 1499, compare_at_price_mvr: 2199, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 7, estimated_delivery_max_days: 14, source_price: 4999, main_image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80", gallery_images: ["https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80"], color_options: ["Jet Black", "Rose Gold", "Silver"], specifications: { display: "1.85\" AMOLED", battery: "7 days", waterproof: "IP68" }, is_featured: true, badges: ["India Pre-order", "Original Brand"] },
  { id: "p3", sku: "MIVI-DUO-PRO", slug: "mivi-duo-pro-speaker", title: "Mivi Duo Pro Portable Speaker", brand: "Mivi", category: "electronics", subcategory: "Speaker", short_description: "Stereo Bluetooth speaker with 24-hour playtime", description: "Designed in India, tested for the tropics. IPX6 waterproof and beach-ready.", price_mvr: 699, compare_at_price_mvr: 999, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 8, estimated_delivery_max_days: 15, source_price: 2299, main_image_url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80", gallery_images: [], color_options: ["Onyx", "Sand"], specifications: { battery: "24h", waterproof: "IPX6" }, is_featured: false, badges: ["India Pre-order"] },
  { id: "p4", sku: "BOAT-STONE-352", slug: "boat-stone-352-speaker", title: "boAt Stone 352 Bluetooth Speaker", brand: "boAt", category: "electronics", subcategory: "Speaker", short_description: "10W IPX7 portable speaker", description: "Built for the beach and the boat. 12-hour playtime with built-in mic.", price_mvr: 549, compare_at_price_mvr: 799, product_type: "ready_stock", stock_status: "in_stock", preorder: false, estimated_delivery_min_days: 1, estimated_delivery_max_days: 3, main_image_url: "https://images.unsplash.com/photo-1610465299996-30f240ac2b1c?auto=format&fit=crop&w=900&q=80", color_options: ["Black", "Red"], specifications: { battery: "12h", waterproof: "IPX7" }, is_featured: true, badges: ["Ready in Maldives", "Fast Sourcing"] },

  // ---- cosmetics
  { id: "p5", sku: "MAMA-VITC-50ML", slug: "mamaearth-vitamin-c-face-wash", title: "Mamaearth Vitamin C Face Wash", brand: "Mamaearth", category: "cosmetics", subcategory: "Skincare", short_description: "Brightening face wash with Vitamin C & Turmeric", description: "Gently cleanses while brightening dull skin. Made safe certified, paraben-free.", price_mvr: 129, compare_at_price_mvr: 199, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 7, estimated_delivery_max_days: 12, source_price: 249, main_image_url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80", gallery_images: [], size_options: ["100ml", "150ml"], specifications: { skin_type: "All", paraben_free: "Yes" }, warranty: "Returns only for damaged items", is_featured: true, badges: ["India Pre-order", "Original Brand"] },
  { id: "p6", sku: "MAMA-SUN-SPF50", slug: "mamaearth-sunscreen-spf50", title: "Mamaearth Ultra Light SPF 50 Sunscreen", brand: "Mamaearth", category: "cosmetics", subcategory: "Skincare", short_description: "Broad-spectrum SPF 50 with Aloe Vera", description: "Lightweight, non-greasy and reef-friendly. Made for tropical sun.", price_mvr: 159, compare_at_price_mvr: 249, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 7, estimated_delivery_max_days: 12, main_image_url: "https://images.unsplash.com/photo-1556228852-80b6e5eeff06?auto=format&fit=crop&w=900&q=80", size_options: ["50ml", "80ml"], is_featured: true, badges: ["India Pre-order", "Best Value"] },
  { id: "p7", sku: "PLUM-NIA-SER", slug: "plum-niacinamide-serum", title: "Plum 5% Niacinamide Serum", brand: "Plum", category: "cosmetics", subcategory: "Skincare", short_description: "Pore minimizing serum with Rice water", description: "Visibly reduces pores and oil. Vegan and cruelty-free.", price_mvr: 219, compare_at_price_mvr: 299, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 8, estimated_delivery_max_days: 14, main_image_url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80", size_options: ["15ml", "30ml"], badges: ["India Pre-order"] },
  { id: "p8", sku: "MAMA-HOIL-200", slug: "mamaearth-onion-hair-oil", title: "Mamaearth Onion Hair Oil 250ml", brand: "Mamaearth", category: "cosmetics", subcategory: "Haircare", short_description: "Hair fall control oil with onion & redensyl", description: "Strengthens hair from the roots. 250ml family-size bottle.", price_mvr: 189, compare_at_price_mvr: 259, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 7, estimated_delivery_max_days: 12, main_image_url: "https://images.unsplash.com/photo-1631730486572-226d1f595b68?auto=format&fit=crop&w=900&q=80", badges: ["India Pre-order", "Original Brand"] },

  // ---- garments
  { id: "p9", sku: "GAR-COT-TSHIRT-01", slug: "premium-cotton-tee", title: "Premium Cotton Crew Tee", brand: "Studio Linen", category: "garments", subcategory: "Casual", short_description: "Heavyweight 240gsm cotton, garment-dyed", description: "Soft hand-feel, drop-shoulder fit. Sourced from Tirupur, India.", price_mvr: 249, compare_at_price_mvr: 349, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 9, estimated_delivery_max_days: 16, main_image_url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80", size_options: ["S", "M", "L", "XL", "XXL"], color_options: ["White", "Sand", "Charcoal", "Ocean"], badges: ["India Pre-order"] },
  { id: "p10", sku: "GAR-MODEST-ABAYA", slug: "modest-pearl-abaya", title: "Pearl Embellished Modest Abaya", brand: "Nida Closet", category: "garments", subcategory: "Modestwear", short_description: "Open-style abaya with pearl trim", description: "Elegant evening abaya tailored for Maldivian women. Premium Nida crepe.", price_mvr: 899, compare_at_price_mvr: 1299, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 10, estimated_delivery_max_days: 18, main_image_url: "https://images.unsplash.com/photo-1604762524889-3e2fcc145683?auto=format&fit=crop&w=900&q=80", size_options: ["S", "M", "L", "XL"], color_options: ["Pearl Black", "Midnight Navy", "Sand"], is_featured: true, badges: ["India Pre-order", "Original Brand"] },
  { id: "p11", sku: "GAR-LINEN-SHIRT", slug: "island-linen-shirt", title: "Island Linen Resort Shirt", brand: "Studio Linen", category: "garments", subcategory: "Casual", short_description: "Pure linen short-sleeve resort shirt", description: "Built for island weather. Breathable and lightweight.", price_mvr: 459, compare_at_price_mvr: 649, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 9, estimated_delivery_max_days: 16, main_image_url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80", size_options: ["S", "M", "L", "XL"], color_options: ["White", "Ocean", "Olive"], badges: ["India Pre-order"] },

  // ---- shoes
  { id: "p12", sku: "SHOE-RUN-FLEX-01", slug: "flex-run-sneakers", title: "Flex Run Performance Sneakers", brand: "Stride", category: "shoes", subcategory: "Running", short_description: "Lightweight running shoes with EVA foam", description: "Engineered mesh upper, EVA midsole and rubber outsole. Daily trainer.", price_mvr: 799, compare_at_price_mvr: 1299, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 9, estimated_delivery_max_days: 16, main_image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80", size_options: ["7", "8", "9", "10", "11"], color_options: ["Black/White", "Navy/Coral", "Grey/Mint"], is_featured: true, badges: ["India Pre-order", "Best Value"] },
  { id: "p13", sku: "SHOE-LIFE-CLASSIC", slug: "classic-lifestyle-sneaker", title: "Heritage Classic Sneakers", brand: "Stride", category: "shoes", subcategory: "Lifestyle", short_description: "Vintage tennis silhouette in white leather", description: "Timeless white sneaker. Goes with everything.", price_mvr: 749, compare_at_price_mvr: 1099, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 9, estimated_delivery_max_days: 16, main_image_url: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80", size_options: ["7", "8", "9", "10", "11"], color_options: ["White", "Off White"], badges: ["India Pre-order"] },
  { id: "p14", sku: "SHOE-BEACH-FLIP", slug: "tropic-beach-flipflop", title: "Tropic Beach Flip Flops", brand: "Atoll", category: "shoes", subcategory: "Sandals", short_description: "Quick-dry beach sandals", description: "Soft EVA footbed and grip outsole. Perfect for resort staff.", price_mvr: 149, compare_at_price_mvr: 249, product_type: "ready_stock", stock_status: "in_stock", preorder: false, estimated_delivery_min_days: 1, estimated_delivery_max_days: 3, main_image_url: "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80", size_options: ["7", "8", "9", "10", "11"], color_options: ["Black", "Coral", "Teal"], badges: ["Ready in Maldives"] },

  // ---- gaming
  { id: "p15", sku: "GAME-HSET-RGB", slug: "phantom-rgb-headset", title: "Phantom RGB Gaming Headset", brand: "Volt", category: "gaming", subcategory: "Headset", short_description: "7.1 surround with RGB lighting", description: "Plush memory foam ear-cups and noise-cancelling mic.", price_mvr: 1199, compare_at_price_mvr: 1899, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 8, estimated_delivery_max_days: 15, main_image_url: "https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=80", color_options: ["RGB Black"], specifications: { audio: "7.1 Surround", mic: "Detachable" }, is_featured: true, badges: ["India Pre-order", "Original Brand"] },
  { id: "p16", sku: "GAME-CTRL-WL", slug: "ace-wireless-controller", title: "Ace Wireless Controller", brand: "Volt", category: "gaming", subcategory: "Controller", short_description: "Bluetooth controller for PC/Mobile", description: "Hall-effect joysticks, low-latency wireless.", price_mvr: 999, compare_at_price_mvr: 1499, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 8, estimated_delivery_max_days: 15, main_image_url: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=900&q=80", color_options: ["Black", "White"], badges: ["India Pre-order"] },
  { id: "p17", sku: "GAME-KEY-MECH", slug: "viper-tkl-mechanical", title: "Viper TKL Mechanical Keyboard", brand: "Volt", category: "gaming", subcategory: "Keyboard", short_description: "75% layout, hot-swappable switches", description: "PBT keycaps, RGB per-key. Compact desk-friendly form-factor.", price_mvr: 1599, compare_at_price_mvr: 2299, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 9, estimated_delivery_max_days: 16, main_image_url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80", color_options: ["Black"], badges: ["India Pre-order"] },

  // ---- musical
  { id: "p18", sku: "MUS-MIC-USB", slug: "studio-usb-mic", title: "StudioCast USB Condenser Mic", brand: "Vox", category: "musical", subcategory: "Microphone", short_description: "Plug-and-play cardioid USB mic", description: "Perfect for podcasts, streaming, and bedroom producers.", price_mvr: 899, compare_at_price_mvr: 1399, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 8, estimated_delivery_max_days: 15, main_image_url: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80", color_options: ["Black"], badges: ["India Pre-order"] },
  { id: "p19", sku: "MUS-GUITAR-AC", slug: "acoustic-cutaway", title: "Acoustic Cutaway Guitar", brand: "Lyra", category: "musical", subcategory: "Guitar", short_description: "Spruce top dreadnought with cutaway", description: "Bright, balanced tone. Great for beginners and gigging.", price_mvr: 2999, compare_at_price_mvr: 3899, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 12, estimated_delivery_max_days: 20, main_image_url: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=900&q=80", color_options: ["Natural", "Sunburst"], is_featured: true, badges: ["India Pre-order", "Custom Sourcing"] },
  { id: "p20", sku: "MUS-SPK-PORTABLE", slug: "lyra-portable-amp", title: "Lyra Portable Busker Amp", brand: "Lyra", category: "musical", subcategory: "Amp", short_description: "Battery-powered 20W amp", description: "Take your sound anywhere. 8-hour battery.", price_mvr: 1799, compare_at_price_mvr: 2299, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 10, estimated_delivery_max_days: 17, main_image_url: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=900&q=80", badges: ["India Pre-order"] },

  // ---- sports
  { id: "p21", sku: "SPT-FOOTBALL-FIFA", slug: "match-football-size5", title: "Match Football Size 5", brand: "Kickstart", category: "sports", subcategory: "Football", short_description: "FIFA quality size 5 match ball", description: "Hand-stitched panels, durable PU exterior.", price_mvr: 299, compare_at_price_mvr: 449, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 8, estimated_delivery_max_days: 14, main_image_url: "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0a72?auto=format&fit=crop&w=900&q=80", badges: ["India Pre-order"] },
  { id: "p22", sku: "SPT-GLOVES-LIFT", slug: "lift-pro-gym-gloves", title: "Lift Pro Gym Gloves", brand: "Kickstart", category: "sports", subcategory: "Gym", short_description: "Leather palm gym gloves", description: "Wrist wraps included. For deadlifts, pulls, and curls.", price_mvr: 199, compare_at_price_mvr: 299, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 7, estimated_delivery_max_days: 14, main_image_url: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80", size_options: ["S", "M", "L", "XL"], badges: ["India Pre-order"] },
  { id: "p23", sku: "SPT-YOGAMAT-6MM", slug: "ocean-yoga-mat-6mm", title: "Ocean Yoga Mat 6mm", brand: "Atoll", category: "sports", subcategory: "Yoga", short_description: "Non-slip TPE yoga mat, 6mm thick", description: "Eco-friendly TPE, anti-tear. Perfect for hot yoga and pilates.", price_mvr: 349, compare_at_price_mvr: 499, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 8, estimated_delivery_max_days: 15, main_image_url: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=900&q=80", color_options: ["Ocean", "Coral", "Sand"], is_featured: true, badges: ["India Pre-order", "Best Value"] },
  { id: "p24", sku: "SPT-CRICKET-BAT", slug: "willow-cricket-bat", title: "Willow Pro Cricket Bat", brand: "Kickstart", category: "sports", subcategory: "Cricket", short_description: "Kashmir willow bat, short-handle", description: "Light pickup, big edges. Tournament ready.", price_mvr: 1199, compare_at_price_mvr: 1599, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 10, estimated_delivery_max_days: 18, main_image_url: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=80", badges: ["India Pre-order"] },

  // ---- extras for category depth
  { id: "p25", sku: "ELEC-CHRG-65W", slug: "rapid-65w-charger", title: "Rapid 65W GaN Charger", brand: "boAt", category: "electronics", subcategory: "Charger", short_description: "Compact GaN PD charger with 3 ports", description: "Charge laptop, phone and earbuds together.", price_mvr: 599, compare_at_price_mvr: 899, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 7, estimated_delivery_max_days: 14, main_image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80", badges: ["India Pre-order"] },
  { id: "p26", sku: "COSM-LIPSTK-MATTE", slug: "matte-lipstick-velvet", title: "Velvet Matte Lipstick", brand: "Nykaa", category: "cosmetics", subcategory: "Makeup", short_description: "Long-stay matte finish lipstick", description: "8-hour wear. Cruelty-free formula.", price_mvr: 99, compare_at_price_mvr: 169, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 7, estimated_delivery_max_days: 12, main_image_url: "https://images.unsplash.com/photo-1631214524020-3c8167274cf4?auto=format&fit=crop&w=900&q=80", color_options: ["Rose", "Coral", "Brick", "Berry"], badges: ["India Pre-order"] },
  { id: "p27", sku: "GAR-KID-TEE", slug: "kids-cotton-tee", title: "Kids' Soft Cotton Tee", brand: "Studio Linen", category: "garments", subcategory: "Kidswear", short_description: "Breathable cotton tee for kids", description: "Designed for tropical comfort.", price_mvr: 149, compare_at_price_mvr: 219, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 9, estimated_delivery_max_days: 15, main_image_url: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80", size_options: ["2T", "4T", "6", "8", "10"], color_options: ["Sky", "Coral", "Cream"], badges: ["India Pre-order"] },
  { id: "p28", sku: "GAME-MOUSE-WL", slug: "viper-light-mouse", title: "Viper Light Wireless Mouse", brand: "Volt", category: "gaming", subcategory: "Mouse", short_description: "Ultralight wireless gaming mouse", description: "59g chassis, 26K DPI sensor.", price_mvr: 1399, compare_at_price_mvr: 1899, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 9, estimated_delivery_max_days: 16, main_image_url: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80", badges: ["India Pre-order"] },
  { id: "p29", sku: "MUS-EARPHONE-WIRED", slug: "tunepods-wired-earphones", title: "TunePods Wired Earphones", brand: "boAt", category: "musical", subcategory: "Earphones", short_description: "Wired in-ear earphones with mic", description: "Crisp bass, in-line mic. Affordable backup pair.", price_mvr: 89, compare_at_price_mvr: 149, product_type: "ready_stock", stock_status: "in_stock", preorder: false, estimated_delivery_min_days: 1, estimated_delivery_max_days: 3, main_image_url: "https://images.unsplash.com/photo-1612444530582-fc66183b16f6?auto=format&fit=crop&w=900&q=80", badges: ["Ready in Maldives"] },
  { id: "p30", sku: "SPT-DUMB-PAIR", slug: "neoprene-dumbbells", title: "Neoprene Dumbbells (Pair)", brand: "Kickstart", category: "sports", subcategory: "Gym", short_description: "Pair of 5kg neoprene dumbbells", description: "Easy-grip, hex shape. Won't roll.", price_mvr: 549, compare_at_price_mvr: 799, product_type: "preorder", stock_status: "preorder", preorder: true, estimated_delivery_min_days: 12, estimated_delivery_max_days: 20, main_image_url: "https://images.unsplash.com/photo-1517344884509-a0c97ec11bcc?auto=format&fit=crop&w=900&q=80", color_options: ["Coral", "Teal"], badges: ["India Pre-order"] },
];

export const REVIEWS = [
  { name: "Aishath M.", island: "Male", rating: 5, comment: "Got my boAt earbuds in 10 days. Original, sealed box. WhatsApp updates were 🔥.", verified: true },
  { name: "Hussain A.", island: "Addu (Hithadhoo)", rating: 5, comment: "Delivered to Hithadhoo without any drama. Best Maldives store I've used.", verified: true },
  { name: "Fathmath I.", island: "Fuvahmulah", rating: 5, comment: "Mamaearth products are hard to find here. Glad this exists!", verified: true },
  { name: "Mariyam Z.", island: "Hulhumale", rating: 4, comment: "Pre-order took 12 days but the price was unbeatable.", verified: true },
];

export const TRENDING_PROMPTS = [
  "Find me original earbuds under MVR 500",
  "Best skincare for oily skin in Maldives heat",
  "Compare these two headphones",
  "Can this deliver to Addu in a week?",
  "Gift ideas for Eid under MVR 800",
  "Build me a student tech bundle",
];

export const FULFILLMENT_STAGES = [
  { key: "order_placed", label: "Order placed", icon: "Receipt" },
  { key: "payment_pending", label: "Payment pending", icon: "CircleDashed" },
  { key: "payment_confirmed", label: "Payment confirmed", icon: "BadgeCheck" },
  { key: "sourcing_from_india", label: "Sourcing from India", icon: "Package" },
  { key: "received_at_india_hub", label: "Received at India hub", icon: "Warehouse" },
  { key: "shipped_to_maldives", label: "Shipped to Maldives", icon: "Plane" },
  { key: "arrived_in_male", label: "Arrived in Male", icon: "MapPin" },
  { key: "sent_to_island_courier", label: "Sent to island courier", icon: "Ship" },
  { key: "out_for_delivery", label: "Out for delivery", icon: "Truck" },
  { key: "delivered", label: "Delivered", icon: "CheckCircle2" },
];
